name: Ejecutar script cada noche

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 2 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar librerías del sistema necesarias para netCDF4
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev libnetcdf-dev libjpeg-dev

      - name: Instalar dependencias del proyecto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script principal
        run: python main.py