name: Ejecutar script cada noche

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 2 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install netCDF4

      - name: Run download script
        run: python A01_source/B01_1_download/La_Palma/download_LaPalma.py