name: Ejecutar script cada noche

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 2 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Necesario para poder hacer push

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias del sistema para netCDF4
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev libnetcdf-dev libjpeg-dev build-essential

      - name: Instalar dependencias del proyecto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar main.py
        run: python main.py

      - name: Hacer commit y push de los .nc
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add A00_data/B_processed/La_Palma/Radiative_Power_by_Year_Month_Day/radiative_power_data.nc || true
          git add A00_data/B_processed/Teide/Radiative_Power_by_Year_Month_Day/radiative_power_teide.nc || true
      
          git diff --cached --quiet || git commit -m "Actualización diaria automática de FRP"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Jesus-Javier-code/Practicas_Empresa_CSIC.git