name: Ejecutar script cada noche

on:
  schedule:
    - cron: '0 2 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar librerías del sistema necesarias para netCDF4
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev libnetcdf-dev libjpeg-dev build-essential

      - name: Instalar dependencias Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar main.py
        run: python main.py

      - name: Subir archivo La Palma
        uses: actions/upload-artifact@v4
        with:
          name: frp_lapalma
          path: A00_data/B_processed/La_Palma/Radiative_Power_by_Year_Month_Day/radiative_power.nc

      - name: Subir archivo Teide
        uses: actions/upload-artifact@v4
        with:
          name: frp_teide
          path: A00_data/B_processed/Teide/Radiative_Power_by_Year_Month_Day/radiative_power_teide.nc