name: Ejecutar script cada noche

on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # <-- Usa una versión más compatible

      - name: Instalar librerías del sistema necesarias
        run: sudo apt-get update && sudo apt-get install -y libhdf5-dev libnetcdf-dev

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar main.py
        run: python main.py