name: Ejecutar script cada noche

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 2 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar librerías del sistema necesarias para netCDF4
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev libnetcdf-dev libjpeg-dev build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python main.py

      - name: Guardar archivo final de FRP
        uses: actions/upload-artifact@v3
        with:
          name: frp_final
          path: 00_data/processed/Radiative_Power_by_Year_Month_Day/radiative_power.nc